spring:
  application:
    name: oauth2-server
server:
  port: 8092
  servlet:
    context-path: /

security:
  oauth2:
    client:
      client-id: tencent
      client-secret: secret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token